name: Extract and Sum HTML Values

on:
  push:
    branches:
      - main

jobs:
  extract-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read HTML File
        id: read_html
        run: cat index.html

      - name: Extract and Sum Values from HTML
        id: extract_values
        run: |
          total=0
          for value in $(grep -oP '(?<=Valor[0-9]: )\d+,\d{2}' index.html); 
          do
            value_number=$(echo $value | sed 's/,/./')
            total=$(echo "$total + $value_number" | bc)
          done
          echo "Total Values Sum: $total"
          echo "Total_valores=$total" >> $GITHUB_ENV

      - name: Display Total Value
        run: echo "The total of all values is: ${{ env.Total_valores }}"
