name: Extract and Sum HTML Values

on:
  push:
    branches:
      - main

jobs:
  extract-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read HTML File
        id: read_html
        run: cat index.html

      - name: Extract and Sum Values from HTML
        id: extract_values
        run: |
          total=0
          # Extract values, convert commas to dots for floating point numbers
          for value in $(grep -oP '(?<=Valor[0-9]: )\d+,\d{2}' index.html); do
            # Replace comma with dot for decimal conversion
            value_number=$(echo $value | sed 's/,/./')
            # Sum the values using bc (basic calculator)
            total=$(echo "$total + $value_number" | bc)
          done
          echo "Total Values Sum: $total"
          # Export the total value to the environment variable
          echo "Total_valores=$total" >> $GITHUB_ENV

      - name: Display Total Value
        run: echo "The total of all values is: ${{ env.Total_valores }}"
